# Generated by Django 5.0.6 on 2024-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='original_box',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
