# Generated by Django 5.0.6 on 2024-06-20 12:22

import django.db.models.deletion
from django.db import migrations, models

def set_default_deck(apps, schema_editor):
    Card = apps.get_model('cards', 'Card')
    Deck = apps.get_model('cards', 'Deck')
    default_deck = Deck.objects.first()
    for card in Card.objects.all():
        card.deck = default_deck
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_original_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck'),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_deck),
    ]
