# Generated by Django 5.0.6 on 2024-06-27 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 9, 58, 31, 233896, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='card',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', max_length=10),
        ),
    ]
