# Generated by Django 5.0.6 on 2024-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
