# Generated by Django 5.0.6 on 2024-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_last_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='total_cards_to_study',
            field=models.IntegerField(default=0),
        ),
    ]
