# Generated by Django 5.0.6 on 2024-06-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_deck_total_cards_to_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='total_cards_to_study',
        ),
    ]
