# Generated by Django 5.0.6 on 2024-06-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_deck_total_cards_to_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='difficulty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='elapsed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='stability',
            field=models.FloatField(default=0.0),
        ),
    ]
