# Generated by Django 5.0.6 on 2024-06-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_difficulty_card_elapsed_days_card_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='card',
            name='elapsed_days',
        ),
        migrations.RemoveField(
            model_name='card',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='card',
            name='stability',
        ),
    ]
