# Generated by Django 5.0.6 on 2024-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_remove_card_difficulty_remove_card_elapsed_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='difficulty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='elapsed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='stability',
            field=models.FloatField(default=0.0),
        ),
    ]
